### PR TITLE
feature (list value): display name of the list node

### PR DESCRIPTION
**Pull request by tobiasschweizer**
display name of the list node

relates to https://github.com/dhlab-basel/Knora/pull/739

### CODE REVIEW

**Comment by sofiag** [comment]
What is this about? Does it relate to the lists GUI? I have been working on this, you can see it under the lists tab. Or is this essentially something different?

**Comment by subotic** [comment]
I think he is simply showing the contents of a list node inside a resource. I don't think that this has anything to do with the admin GUI.

**Comment by tobiasschweizer** [comment]
> I think he is simply showing the contents of a list node inside a resource. I don't think that this has anything to do with the admin GUI.

Exactly: it just shows the label of a node a list value points to :-)

**Comment by sofiag** [comment]
oh ok! Do you need it to be reviewed?

**Comment by tobiasschweizer** [comment]
The thing is that it depends on https://github.com/dhlab-basel/Knora/pull/739

We have to decide if the refactoring for `SparqlExtendedConstructResponse ` should be done in the open PR or postponed. The problem is that we need the PR for the BEOL beta release.

**Pull request merged**
