### PR TITLE
Create / Update user and add it to a project

### LINKED ISSUE #128: Edit user profile
Missing part in user-form: edit user; it doesn't work at the moment

### LINKED ISSUE #182: Problems in Add new team member tab
When adding a new team member: 

- If I select to add existing user, the user does not show up in the last card (submit data) and it is not possible to save
- There are styling problems: the close and visibility buttons on add existing user and on setting password show up as words not icons

screen shot 2018-03-05 at 11 19 32
screen shot 2018-03-05 at 11 19 48
screen shot 2018-03-05 at 11 20 27

### PR DESCRIPTION
**Pull request by kilchenmann**
fixes #128
fixes #182

### CODE REVIEW

**Comment by kilchenmann** [comment]
resolves #128

**Comment by kilchenmann** [comment]
fixes #128

**Comment by kilchenmann** [comment]
resolves #182

**Comment by sofiag** [comment]
Do you still need a review on this? I saw yesterday you were still working on it...

**Comment by kilchenmann** [comment]
yes please

**Comment by kilchenmann** [comment]
> At the end of the last step (both in create and edit) there should be a button to close the dialogue and the page should reload to show updated user list (with
location.reload(); ).
Yes that's true. I wanted to do this.

> Should edit have an option to change user from member to admin and vice versa?
Edit group membership is a bit complicate, because there's no "put" in Knora group api; only post and delete. In this case, I have to know the state of the group membership of the user. Anyway, edit group permission should be done somewhere else. It's a bit an issue, when the user is already member of the project, I know. 

Should I fix it now, or in the next release? End of April. Because these are small issues. And changing the group permission will be done when we're working on the group-form component.

**Comment by kilchenmann** [comment]
Is it possible to approve it now and I will write a new issue with your concerns to be fixed in next release: https://github.com/dhlab-basel/Salsah/milestone/8

**Comment by sofiag** [comment]
It is fine to fix it later, since this is anyway working now. Maybe at least adding the location.reload(); after closing the dialogue, cause it can confuse the user to think the changes did not take place... For the rest it's ok.

**Comment by kilchenmann** [comment]
Thanks 👍🏻

**Comment by subotic** [comment]
Didn't I specifically [ask everybody](https://github.com/orgs/dhlab-basel/teams/dasch/discussions/7) 2 hours ago not to merge anything until I'm finished with releasing? Or do you think that this does not apply to you?

**Comment by kilchenmann** [comment]
I'm sorry, but I didn't saw that: https://github.com/orgs/dhlab-basel/teams/dasch/discussions/7

**Comment by subotic** [comment]
Then turn on the email notifications back on or whatever you need to do to make sure this doesn't happen again. Github is our main way of communication.

**Comment by kilchenmann** [comment]
They are turned on, and I get commits message and everything but not this team discussion info. And I was looking now everywhere in my email accounts. I also checked the notification settings, but never saw those team discussion messages.

**Pull request merged**
