### PR TITLE
Accept Knora API graph responses

### PR DESCRIPTION
**Pull request by benjamingeer**
This PR adapts the processing of JSON-LD to the changes in https://github.com/dhlab-basel/Knora/pull/851.

### CODE REVIEW

**Comment by benjamingeer** [comment]
I don’t know what you mean. Are those configuration settings somewhere?

**Comment by tobiasschweizer** [comment]
These are the test scenarios in the spec files, e.g., `src/app/model/services/ontologycache.service.spec.ts`. 

We can look at it on Monday.

**Comment by tobiasschweizer** [comment]
@benjamingeer I have fixed all failing tests, I am now changing the test data set so it can be re-created from Knora in the future.

**Comment by benjamingeer** [comment]
@tobiasschweizer Thank you, I will buy you a beer. 😃🍺

**Pull request merged**
