### PR TITLE
reafctor (ontology cache): adapt ontology cache service

### PR DESCRIPTION
**Pull request by tobiasschweizer**
adaptions needed for https://github.com/dhlab-basel/Knora/pull/755

### CODE REVIEW

**Comment by subotic** [comment]
@tobiasschweizer could you please move `src/app/model/services/test-data/ontologycache` to the existing `test-data` folder located at `src/app/model/test-data`. thanks.

**Comment by tobiasschweizer** [comment]
@subotic will do, no problem!

**Comment by tobiasschweizer** [comment]
> could you please move src/app/model/services/test-data/ontologycache to the existing test-data folder located at src/app/model/test-data. thanks.

@subotic done in  https://github.com/dhlab-basel/Salsah/pull/190/commits/451ac03b8722955d350e5a1e40139a4dc96e2bad

**Comment by subotic** [comment]
thanks :-)

**Pull request merged**
