### PR TITLE
Wip/move node delete button #28

### PR DESCRIPTION
**Pull request by sofiag**
The node delete button is now in the edit node dialogue box

### CODE REVIEW

**Comment by kilchenmann** [comment]
I will review it asap

**Comment by kilchenmann** [comment]
I get the following errors:
`ERROR in src/app/view/modules/form/edit-node-info/edit-node-info.component.ts(149,23): error TS2339: Property 'push' does not exist on type '() => FormArray'.`

`src/app/view/modules/form/edit-node-info/edit-node-info.component.ts(153,23): error TS2339: Property 'removeAt' does not exist on type '() => FormArray'.`

**Comment by kilchenmann** [comment]
OK, I found the bug and I fixed it

**Comment by kilchenmann** [comment]
I made some changes and I fixed style issues. @sofiag can you test ist?

**Comment by sofiag** [comment]
@kilchenmann  ok I'll test it again now

**Comment by sofiag** [comment]
@kilchenmann  What did you change exactly? It all works fine, but the spacing between the nodes in the list view is at the moment too big... It's just a styling issue I guess so we can also change it later. Shall I merge?

**Comment by sofiag** [comment]
@kilchenmann by the way, the error you encountered, I had corrected it earlier, maybe I forgot to push it before I left... The methods that were using it are not in use anymore, so we could just remove them.

**Comment by kilchenmann** [comment]
Yes I think, we can merge. I will approve it

**Pull request merged**
