### PR TITLE
feature (salsah): Update to new admin API

### LINKED ISSUE #153: `Salsah develop` will not work with `Webapi develop`
A lot of changes to the `users`, `projects`, and `groups` endpoint, which need to be added to the corresponding `services` in SALSAH.

### PR DESCRIPTION
**Pull request by subotic**
### Summary

- The `webapi` server `admin` API has changed. This PR provides the necessary changes.
- Added integration tests and shared test data for admin api

### Issues

- resolves #153

### CODE REVIEW

**Comment by subotic** [comment]
@kilchenmann Are you completely gone the next two weeks? Should I better ask @sofiag to review?

**Comment by kilchenmann** [comment]
I just fixed some merge conflicts, after updating your branch.

**Comment by subotic** [comment]
@kilchenmann thanks. I will look into it. As a gentle reminder, it would be really helpful to have at least some basic tests, so that you don't need to go the whole application by hand.

**Comment by subotic** [comment]
@kilchenmann the two routes work now.

**Pull request merged**
