### PR TITLE
Update README and documentation

### LINKED ISSUE #246: Questions about installation
## yarn or npm?

The [README](https://github.com/dhlab-basel/Salsah/blob/develop/README.md) says to use `yarn` instead of `npm`, but the [Sphinx docs](https://dhlab-basel.github.io/Salsah/documentation/guidelines/rst/get-started.html) say to use `npm`.

## yarn install errors

```
$ yarn install --production=false

yarn install v1.6.0
(node:12105) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error lcov-result-merger@2.0.0: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
```

The README says I need Node 6.9.0 or higher, which I have:

```
$ node --version
v10.0.0
```

## ng serve fails

```
$ ng serve
Local workspace file ('angular.json') could not be found.
Error: Local workspace file ('angular.json') could not be found.
    at WorkspaceLoader._getProjectWorkspaceFilePath (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:37:19)
    at WorkspaceLoader.loadWorkspace (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:24:21)
    at ServeCommand._loadWorkspaceAndArchitect (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:195:32)
    at ServeCommand.<anonymous> (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:47:25)
    at Generator.next (<anonymous>)
    at /Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:3:12)
    at ServeCommand.initialize (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/architect-command.js:46:16)
    at Object.<anonymous> (/Users/benjamingeer/.config/yarn/global/node_modules/@angular/cli/models/command-runner.js:87:23)
```

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves #246 
- new documentation with jekyll instead of sphinx
- update readme (node version and yarn)

### CODE REVIEW

**Comment by kilchenmann** [comment]
yes of course... i can do that

**Comment by kilchenmann** [comment]
It's done.

> Do you also want to support a local build of the docs files or only support the live preview?

I think we don't need to support the local build. Or what do you mean with live preview?

**Comment by tobiasschweizer** [comment]
I think in Knora there are different options: you can start the live server or just generate the files.

**Comment by kilchenmann** [comment]
Yes with `bundle exec jekyll serve`you start a live server, which builds the files in the `_site`-directory. For the GitHub pages we don't need this folder, as the site-files are created directly on the Github server. That's the advantage of Jekyll.

**Comment by tobiasschweizer** [comment]
Do you want to add the build of the docs to travis?

**Comment by kilchenmann** [comment]
I don't think so...

**Pull request merged**
