### PR TITLE
Highlight search terms for fulltext search

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Highlight search terms of a fulltext search using the NIE-INE module.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@janCstoffregen Could we add a configuration option to the highlight module so that some markup elements are not manipulated?

 We present math within `<span class"math">LaTeX code</span>` and its content should not be altered. If someone searches for left, `\left` should not be highlighted because this breaks the LaTeX and it cannot be rendered by MathJax. Example: <http://api.02.unibas.dasch.swiss/v2/search/left?offset=0>

Maybe we should also think about only displaying the highlighted terms and some context, clipping the rest. But this is difficult because we could destroy the markup quite easily.

It is cool that we can put this logic in an npm module :-) Nice work!

**Comment by janCstoffregen** [comment]
Hi, yes, I can try. I'll create an issue on our npm repo and link it here.
https://github.com/nie-ine/npm-package/issues/9

**Comment by tobiasschweizer** [comment]
@janCstoffregen great, let me know if I can help

**Comment by janCstoffregen** [comment]
ok, I'll let you know when I start, I planned it for the beginning of next week.

**Comment by kilchenmann** [comment]
What's the status of this PR?

**Comment by janCstoffregen** [comment]
@tobiasschweizer informed me that this will happen and be implemented on the server side. please confirm.

**Comment by kilchenmann** [comment]
When this will happen on the server side, we will close this PR without merging

**Comment by benjamingeer** [comment]
Server support depends on https://github.com/dhlab-basel/Knora/issues/913, which depends on https://github.com/dhlab-basel/Knora/issues/926.

**Comment by kilchenmann** [comment]
Thanks @benjamingeer for linking the related issues.

**Pull request closed without merging**
