### PR TITLE
CREATE new list 

### PR DESCRIPTION
**Pull request by sofiag**
CREATE new list component and add it to the framework-for-listings and form-dialog components to activate new list form dialog

### CODE REVIEW

**Comment by sofiag** [comment]
This should be complete now, I created one form (list-form) for editing list info and creating new list. The services for create new list and editing lists need to be created still @subotic, while there are some issues with the service for updating list Info, dealt with in issue #209. 
If this looks ok, I would like to merge.

**Comment by subotic** [comment]
also, the tests on Travis are failing

**Comment by sofiag** [comment]
Damn, I thought I had fixed the problems with the tests...

**Comment by sofiag** [comment]
@subotic I will look into it. They should all go in the spec.ts file right?

**Comment by sofiag** [comment]
@subotic @kilchenmann I am not sure how to implement extra tests correctly and I don't want to mess up this PR while the current test are passing. Besides, I need to work on implementing list and node edit only for administrator user. My plan was to work on that after this PR. Can we merge this now, and we can look at the tests together when I'm in the office? (I am on home office due to the move but can drop by whenever you have time).

**Comment by sofiag** [comment]
@subotic Can I merge?

**Comment by subotic** [comment]
sorry, yes.

**Comment by sofiag** [comment]
@subotic @kilchenmann Have you changed the permissions of the repository? I am not able/allowed to merge my PR!!:

screen shot 2018-03-22 at 08 58 21

**Comment by subotic** [comment]
can you try now?

**Comment by sofiag** [comment]
No, still not...

**Comment by subotic** [comment]
maybe now?

**Comment by sofiag** [comment]
no... weird...

**Comment by subotic** [comment]
now it should work.

**Comment by sofiag** [comment]
yes! what was the problem?

**Comment by subotic** [comment]
I changed the settings :-)

**Comment by sofiag** [comment]
thx!

**Pull request merged**
