### PR TITLE
Fix: update version of search and core module

### LINKED ISSUE #143: show number of all results (count query)
For each search, a count query is performed to get the total number of results (not just the number of results returned by the first page of results).

The number of all results should be displayed, so the user knows that there are more results he could get.

### LINKED ISSUE #198: Building with '--prod' fails
Building Salsah2 for production 

```
$ ng build --prod --env=prod
```

fails with the following error:

```
ERROR in : Unexpected value 'MatJDNConvertibleCalendarDateAdapterModule in /Users/subotic/_github.com/Salsah/node_modules/jdnconvertiblecalendardateadapter/dist/index.d.ts' imported by the module 'AppModule in /Users/subotic/_github.com/Salsah/src/app/app.module.ts'. Please add a @NgModule annotation.
```

### PR DESCRIPTION
**Pull request by kilchenmann**
- Fix bugs from core and search module. Extended search should work now.
- Update README

resolves #198, resolves #143

### CODE REVIEW

**Comment by flavens** [comment]
[Update to Angular 6](https://trello.com/c/NF54pdky/1-update-to-angular-6)

**Comment by kilchenmann** [comment]
> I am getting several issues with the extended search:
> - no automatic drop-down list for a property type text
> - got the error TypeError: Cannot read property 'toUpperCase' of undefined when searching with a date (datepicker)

@flavens Can you try to fix this? Or should I?

**Comment by flavens** [comment]
@kilchenmann I am working on it with Tobias!

**Comment by kilchenmann** [comment]
I will merge this, when I have update the version in package.json

**Comment by kilchenmann** [comment]
💩 travis; I mean I only changed the version number in package.json, but Travis had again a timeout error.

**Pull request merged**
