### PR TITLE
fix (extended search results): remove knarql string in search results

### LINKED ISSUE #188: Remove Looked For from template
Looked For and its corresponding URI should be just visible in case of full text search

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves #188

### CODE REVIEW

**Comment by SepidehAlassi** [comment]
@tobiasschweizer that would be the ideal case, but if Andre thinks otherwise, we can live with it for beta release.

**Comment by tobiasschweizer** [comment]
So we should merge it?

**Comment by tobiasschweizer** [comment]
@kilchenmann I noticed that the busy symbol does not disappear when no results are found:

screen shot 2018-03-07 at 5 49 42 pm

Is that new?

**Comment by kilchenmann** [comment]
No, it should disappear; on my computer it does.

**Comment by tobiasschweizer** [comment]
@kilchenmann could you try http://iml-leonhard.iml.unibas.ch/search/fulltext/gaga?

**Comment by tobiasschweizer** [comment]
iml-leonhard uses the dist (ng build)

**Comment by kilchenmann** [comment]
It seems there's an error with the MessageComponent. It makes a console.log because of an ApiServiceError (line 112) in message.component.ts.
I suggest to merge this PR now and tomorrow I will have a look on the issue with the message component

**Pull request merged**
