### PR TITLE
prepare adaption to new ontology route message format

### PR DESCRIPTION
**Pull request by tobiasschweizer**
coordination with https://github.com/dhlab-basel/Knora/pull/670

- [x] adaption of `ontologycache.service.ts` to new ontology route message format

### CODE REVIEW

**Comment by benjamingeer** [comment]
In https://github.com/dhlab-basel/Knora/pull/670, ontology responses look like this:

* simple schema: https://github.com/dhlab-basel/Knora/blob/c3a4fb3c6faef04f4b375882b30af21958477062/webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologySimple.json
* value objects schema: https://github.com/dhlab-basel/Knora/blob/c3a4fb3c6faef04f4b375882b30af21958477062/webapi/src/test/resources/test-data/ontologyR2RV2/incunabulaOntologyWithValueObjects.json

**Comment by benjamingeer** [comment]
If you asked for multiple ontologies, the object of `knora-api:hasOntologies` is an array.

**Comment by tobiasschweizer** [comment]
Now that I think about it again: The change will only affect writing the data to the cache, read operations from the cache will stay the same. So I guess this should not be too hard to do.

**Comment by benjamingeer** [comment]
Things renamed in `knora-api`:

* `IntegerValue` -> `IntValue`
* `integerValueAsInteger` -> `intValueAsInt`

**Comment by tobiasschweizer** [comment]
@benjamingeer is this ok?

**Pull request merged**
