### PR TITLE
feature (salsah): admin api (part 6)

### PR DESCRIPTION
**Pull request by subotic**
### Summary
The format of project description and keywords has changed in the `webapi`.  This PR adds changes to the project data model (project description and and keywords).

To be able to test, please use the `wip/admin-api-6` branch (https://github.com/dhlab-basel/Knora/tree/wip/admin-api-6) from the Knora repository.

### CODE REVIEW

**Comment by sofiag** [comment]
I'm tried to check this, but I could not reStart sbt on Knora webapi, branch wip/admin-api-6. I get 
"
webapi[ERROR] Exception in thread "main" akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://webapi/user/responderManager#-1436882849]] after [360000 ms]. Sender[null] sent message of type "org.knora.webapi.messages.v2.responder.ontologymessages.LoadOntologiesRequestV2".
"

and ends with 
"
webapi ... finished with exit code 255

"

**Comment by subotic** [comment]
Also it is important to start `webapi` with `reStart allowReloadOverHTTP`.

Then you can run the integration tests like so: `ng test --reporters=spec --browser=ChromeHeadless --single-run=true --env=it`

**Comment by subotic** [comment]
@sofiag @kilchenmann there is still an issue with the project description. I tried to fix it, but I don't know where.

**Comment by sofiag** [comment]
@subotic The commit above fixes this.

**Comment by subotic** [comment]
thanks.

**Pull request merged**
