### PR TITLE
feature (user password): user password change by sys admin

### LINKED ISSUE #261: Sys admin can change user password
The system administrator should be able to change a user's password if necessary.

### PR DESCRIPTION
**Pull request by sofiag**
resolves #261

### CODE REVIEW

**Comment by sofiag** [comment]
This is ready, the submit methods for changing the password by sys Admin does not work yet because I am waiting for the new update service from knora-ui. It is now commented out in the .ts file. We can merge this and replace the methods once the knora-ui is implemented.

**Comment by kilchenmann** [comment]
I will have a look on it next week...

**Comment by sofiag** [comment]
I'm confused about the test failing, if I do it on the terminal I get no errors...

**Comment by sofiag** [comment]
ok, it just needed to re-run. The problem came from the extended-search.component that was taking too long to respond at first. Maybe this is something to keep in mind?

**Comment by kilchenmann** [comment]
I got a "Bad request" when I update another user. The IRI of the user which I wanted to update is undefined: /admin/users/undefined

**Comment by sofiag** [comment]
@kilchenmann  It should work now, can you check?
(the new service function updateUsersPassword does not work with Knora yet... )

**Comment by sofiag** [comment]
@kilchenmann can I merge this?

**Comment by kilchenmann** [comment]
I didn't had the time yet to look at it... I can do it in the afternoon

**Comment by kilchenmann** [comment]
I still get an error on project page because of undefined user iri. 
On the system page a get the following error:

> org.knora.webapi.ForbiddenException: The supplied password does not match the requesting user's password.

This problem comes probably from somewhere else (API issue). But it should be anyway handled in the frontend: show it as an error message. Should I try to fix that?

**Comment by sofiag** [comment]
This is strange, at work I was not getting any errors when I committed, now I see it also at my laptop. I have to check when I am there on Monday...

**Comment by subotic** [comment]
> This problem comes probably from somewhere else (API issue).

I doubt that. Usually, the errors returned by the Knora API are correct (there are tests in place that also check for correct error responses). I would look for the error either in the service or in the component.

**Comment by sofiag** [comment]
The problem is the submit method. I see here that the changes I made on Wednesday at work are not showing up, so maybe I didn't push it properly before I left on Wednesday. I'll look at it from the office on Monday and we can merge it then...

**Comment by sofiag** [comment]
ok, I know what went wrong, I accidentally made a new branch at the last commit, wip/password-change-by-sysAdmin instead of wip/password-change-by-sysadmin. I knew the command git checkout -b <branch> for making a new branch, but apparently git checkout <branch> is a shortcut for the same when the branch does not exist, and I didn't notice the typo. I'll fix it on Monday and then we can merge.

**Comment by subotic** [comment]
@sofiag please don't forget to remove the `wip/password-change-by-sysAdmin` branch from Github.

**Comment by sofiag** [comment]
It should be ready now, @kilchenmann

**Comment by kilchenmann** [comment]
It works in system view, but not yet in project view... The user iri is still undefined there.

**Comment by sofiag** [comment]
I see what the problem is. We always send the user information, but in the case of the project view the user is not the same as the logged in user. Maybe we can talk about it tomorrow when you are here.

**Comment by kilchenmann** [comment]
What's the status of this PR?

**Comment by sofiag** [comment]
It still works in system view but not in project view. Maybe it has to do with the information required by the updateUser function in the UsersService.

**Comment by sofiag** [comment]
The travis tests are still failing...

**Comment by kilchenmann** [comment]
I know and I'm working on it right now. It's a timeout error, which is not easy to fix

**Comment by sofiag** [comment]
ok! I'll merge it after lunch then, when it's ready.

**Comment by kilchenmann** [comment]
The tests were running locally without error.

**Pull request merged**
