### PR TITLE
Wip/extended search v2 form 2

### PR DESCRIPTION
**Pull request by tobiasschweizer**
Create a GUI form to author an extended search query and create KnarQL from it.

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
1. `SelectPropertyComponent` currently only supports the selection of one property (HTML selection). Instead, multiple selections (SelectPropertyComponent) may be allowed if the properties have the same object class constraint.  Use case: the user wants to specify the target of a linking property but would like to restrict the property to two Iris (logical OR).

The KnarQL could look like this:

```
        ?letter ?linkingProp1  ?person1 .
        
        FILTER(?linkingProp1 = beol:hasAuthor || ?linkingProp1 = beol:hasRecipient )
        
        ?person1 a beol:person .
```

2. Another case of a logical OR would be the specifications of two or more independent combinations of property, comparison operator and value. That could be represented as a UNION in KnarQL.

**Comment by tobiasschweizer** [comment]
There is a problem with the node moduls `jdnconvertiblecalendar` and `jdnconvertiblecalendardateadapter`. They contain no compile instructions.

A tsconfig.json is needed so that the angular project knows how to build them.

**Comment by tobiasschweizer** [comment]
[GUI](https://trello.com/c/vYWqfech/10-gui)

**Comment by tobiasschweizer** [comment]
I solved the problem with the missing compile instructions by providing npm modules:

- https://www.npmjs.com/package/jdnconvertiblecalendar
- https://www.npmjs.com/package/jdnconvertiblecalendardateadapter

However, the latter should be built as an Angular module.

**Comment by tobiasschweizer** [comment]
@ezbinden Could we add the code that closes the extended search form window when a query has been submitted?

**Comment by tobiasschweizer** [comment]
@ezbinden also we should use the translation service you added for the labels in the extended search from

**Comment by tobiasschweizer** [comment]
@ezbinden https://github.com/dhlab-basel/Salsah/pull/109/commits/534a8374f884ceea5fb5c7ab6e2700ad4ea38374 should fix the problem that the form remains valid although the property changed.

**Comment by kilchenmann** [comment]
resolves #142  
closes #148

**Comment by tobiasschweizer** [comment]
@kilchenmann Is this ok? Can it be merged?

**Comment by kilchenmann** [comment]
I have to look on it. I will do it today

**Comment by tobiasschweizer** [comment]
@kilchenmann Great, thx.!

**Comment by tobiasschweizer** [comment]
> it works fine and makes what it should

glad to hear that :-)

**Pull request merged**
