### PR TITLE
REMOVE depricated list-form-component

### PR DESCRIPTION
**Pull request by sofiag**
We are no longer using the list-form-component, instead we have the edit-list-info and the edit-node-info components.

### CODE REVIEW

**Comment by kilchenmann** [comment]
Do you still need my review?

**Comment by sofiag** [comment]
Thanks, I am just not decided yet if I should just keep this component and move the edit-list-info component to it, then get rid of the latter instead. The idea being as you said @kilchenmann that there should be one form both for edit and create new list... I'll decide soon and either merge or remove this PR, is both ok?

**Comment by sofiag** [comment]
As it is now list-form is not used at all, it is only a matter of keeping it because it has a better name...

**Comment by sofiag** [comment]
I am closing this without merging, since I implemented the necessary in the create-new-list PR.

**Comment by kilchenmann** [comment]
Can we delete this branch?

**Comment by sofiag** [comment]
same here, sorry, I actually thought they delete when I close the PR...

**Pull request closed without merging**
