### PR TITLE
fix (dialog in beol): close button

### LINKED ISSUE #187: close button for dialog
Dialog is used in the following directives and components. The close button is missing.

- src/app/view/modules/other/mathjax.directive.ts
- src/app/view/modules/form/contact-form/contact-form.component.ts

### PR DESCRIPTION
**Pull request by kilchenmann**
fixes #187

### CODE REVIEW

**Comment by kilchenmann** [comment]
It should be fixed now. Can you @tobiasschweizer review it.

**Comment by tobiasschweizer** [comment]
Ok will do it asap! Thx!

**Comment by kilchenmann** [comment]
Btw I can't test it in MathJax, because I don't have a nice example resp. I don't have the BEOL data.

**Comment by tobiasschweizer** [comment]
> Btw I can't test it in MathJax, because I don't have a nice example resp. I don't have the BEOL data

no problem, I can do that

I added a commit that introduces the change to other parts where it is needed (outgoing and incoming links) and adds a function that creates the configuration object so we do not have redundant code.

**Comment by tobiasschweizer** [comment]
could you look at https://github.com/dhlab-basel/Salsah/pull/189/commits/41cb6519431e21f4cf151eff0d77a50620ee042b and tell if it looks ok to you?

**Comment by tobiasschweizer** [comment]
it looks really great now, thanks a lot!

**Comment by kilchenmann** [comment]
Thanks. It works here. If you like, you can merge it...

**Comment by tobiasschweizer** [comment]
great, I will merge as soon as the tests have passed

**Pull request merged**
