### PR TITLE
Entity Iris are now objects in JSON-LD

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR relates to https://github.com/dhlab-basel/Knora/pull/833.

- entity Iris are not strings, but objects (ontology response in JDON-LD)
- `schema:name` has been replaced by `rdfs:label`

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
```
case AppConfig.ListValue:
 
                 let listValue: ReadListValue = new ReadListValue(
                     propValue['@id'],
                     propIri,
                     propValue[AppConfig.listValueAsListNode],
                     propValue[AppConfig.listValueAsListNodeLabel]
                 );
 
                 valueSpecificProp = listValue;
 
                 break;
```

It should be `propValue[AppConfig.listValueAsListNode]['@id']`

**Comment by benjamingeer** [comment]
What exactly should I try? Should I run automated tests? If so, how do I run them?

**Comment by tobiasschweizer** [comment]
The automated the tests are run be travis. You can run them locally like this `ng t`

Could you try `ng s` and use the GUI with your Knora PR?

**Comment by benjamingeer** [comment]
"Use the GUI" is a bit vague. I can click on random things, but since I don't know how they're supposed to work, I don't think I can test the GUI manually.

**Comment by tobiasschweizer** [comment]
You can search for a resource in the GUI and see if it is displayed correctly. 

There are already some tests for the ontology cache service. 

But we should add more. Would you be interested in doing that?

**Comment by benjamingeer** [comment]
> You can search for a resource in the GUI and see if it is displayed correctly.

How will I know if it's displayed correctly?

**Comment by benjamingeer** [comment]
> But we should add more. Would you be interested in doing that?

I think that it's best if the people who wrote the code write the tests for it...

**Comment by tobiasschweizer** [comment]
Open the browser console to check for errors.

What I did was: I created an `anything:Thing` with Salsah1 and added different values of different types and then searched for that in Salsah2.

**Comment by benjamingeer** [comment]
> Open the browser console to check for errors.

What if there are no errors, but the resource is displayed wrong, but I don't know that, because I don't know how it's supposed to look?

**Comment by tobiasschweizer** [comment]
> I think that it's best if the people who wrote the code write the tests for it...

Ideally yes. But I simply have very scarce time resources, still I had to add all this functionality because it was not there yet and we needed it for BEOL (all for all the other projects).

So if could dedicate some time, that would be great. Also because you surely will have good suggestions how to improve it. We can look at it together and then see whet is realistic.

**Comment by benjamingeer** [comment]
I also have very scarce time resources and I'm supposed to finish API v2. But when I write code, I write tests for it. I thought we had all agreed on that as part of our development process in the DHLab.

**Comment by tobiasschweizer** [comment]
> I also have very scarce time resources and I'm supposed to finish API v2. But when I write code, I write tests for it. I thought we had all agreed on that as part of our development process in the DHLab.

Sure, I understand. Can I at least explain the design of SALSAH2 to you, so we can figure out what the design documentation should look like?

Also I can show you the tests I have written so fare and you could give me some feedback on that.

**Comment by benjamingeer** [comment]
I'd be glad to try to understand a bit about how the GUI works and perhaps make some suggestions. But I don't think I can actually work on GUI development and still get API v2 done in a reasonable amount of time, unless Lukas decides that he wants priorities to change.

**Comment by tobiasschweizer** [comment]
> I'd be glad to try to understand a bit about how the GUI works and perhaps make some suggestions. But I don't think I can actually work on GUI development and still get API v2 done in a reasonable amount of time, unless Lukas decides that he wants priorities to change.

I think it would be great if I could give you some insight in the service that parsers the ontology JSON-LD responses and the mapping from JSON-LD to internal classes for resources and values. It is quite probably that there will be future changes in Knora that require more changes on the side of SALSAH2.

I will be glad to start a documentation for it and also write more test, but I can only do it step by step.

**Comment by tobiasschweizer** [comment]
I will try to add some more tests to this PR:

**Comment by benjamingeer** [comment]
I would really like to merge https://github.com/dhlab-basel/Knora/pull/833 today if possible, because's blocking other things that I need to work on. Could you make a new PR for SALSAH 2 tests instead?

**Comment by tobiasschweizer** [comment]
> Could you make a new PR for SALSAH 2 tests instead?

Yes, absolutely.

**Comment by tobiasschweizer** [comment]
but you still have to approve this PR

**Pull request merged**
