### PR TITLE
infinite scroll in search results

### LINKED ISSUE #142: Infinite Scroll
We have to implement (or doing it by ourselves) an infinite/endless scroll module. 
e.g. https://github.com/orizens/ngx-infinite-scroll
or https://codeburst.io/angular-2-simple-infinite-scroller-directive-with-rxjs-observables-a989b12d4fb1

### PR DESCRIPTION
**Pull request by kilchenmann**
resolves #142

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
I integrated that here: https://github.com/dhlab-basel/Salsah/pull/109

It was easier to copy and paste some code than merging my PR into this one.

**Comment by kilchenmann** [comment]
When you integrated it into #109, then we can close this pull request without merging? Is that right?

**Comment by tobiasschweizer** [comment]
@kilchenmann 

> When you integrated it into #109, then we can close this pull request without merging? Is that right?

Yes. Once you have reviewed #109 we can close this PR without merging it.

**Comment by tobiasschweizer** [comment]
@kilchenmann ok, you can close this PR without merging

**Pull request closed without merging**
