### PR TITLE
Cleanup lists code / show edit on hover

### PR DESCRIPTION
**Pull request by sofiag**
resolves #237

### CODE REVIEW

**Comment by sofiag** [comment]
Do we still need the list-node-form.component? For the time being all showing and editing operations of the list take place in the lists-list, list-form and node-form components. @subotic @kilchenmann can I remove it?

**Comment by kilchenmann** [comment]
I think you can remove it... or if you're not sure, set it to deprecated (by renaming it).

**Comment by sofiag** [comment]
Again I get a fail in the travis tests, I have no idea why, any clues, @kilchenmann ?
When the tests are fixed, this PR is ready, check the appearance of the list itself and the list and node forms please.

**Comment by kilchenmann** [comment]
The error said: ERROR in src/app/app.module.ts(298,9): error TS1005: ',' expected.

**Comment by kilchenmann** [comment]
Did you run the test locally as well? I try to run it now

**Comment by sofiag** [comment]
You are right, sorry I didn't see it (I was going through the highlighted parts...). Indeed there was this error in the app.module, I wonder why the code worked in the first place. No I didn't run it locally yet.

**Comment by kilchenmann** [comment]
When the test runs through on your local machine, then it should also run through in travis

**Comment by kilchenmann** [comment]
I will review it later...

**Comment by sofiag** [comment]
ok thx

**Comment by sofiag** [comment]
ok, I didn't remove them on purpose because I thought they might come in useful, but I'll comment them out...

**Comment by sofiag** [comment]
It is fixed now.

**Comment by kilchenmann** [comment]
you can merge it

**Pull request merged**
