### PR TITLE
add salsah-link class to span representing an internal link

### PR DESCRIPTION
**Pull request by tobiasschweizer**
use class "salsah-link" for internal links

closes: #225

### CODE REVIEW

**Comment by kilchenmann** [comment]
But why did you define the salsah-link class in the app configuration? And don‘t use it directely?

**Comment by tobiasschweizer** [comment]
> But why did you define the salsah-link class in the app configuration? And don‘t use it directely?

Because I use it in other places too (e.g., mathjax.directive). In case this changes, it is still consistent.

**Comment by tobiasschweizer** [comment]
@kilchenmann OK?

**Comment by kilchenmann** [comment]
yes ok. it was just a question. you can merge it.

**Pull request merged**
