### PR TITLE
Adapt json-ld conversion

### LINKED ISSUE #281: Adapt decimal and anyUri
Changes introduced by https://github.com/dhlab-basel/Knora/pull/927 will require the following adaptions in SALSAH:

- JSON-LD conversion:
    - `DecimalValue` is now an object, not a string
    - `URIValue` is now an object, not a string

Check if the test data (both ontology and data) has to be updated.

### PR DESCRIPTION
**Pull request by tobiasschweizer**
This PR provides the necessary changes for the conversion of JSON-LD representation of resources with values in order to comply with 
https://github.com/dhlab-basel/Knora/pull/927.

Necessary changes:
- [x] ignore certain properties when handling values (lastModificationDate, creationDate, attachedToUser, attachedToProject, hasPermissions). These must be included once the GUI supports value updates and creation.
- [x] adapt conversion of decimal and Uri values (objects with member `@value`)
- [x] adapt test data  

The changes only cover data representation, not the ontologies. If the ontologies are affected too, additional changes may be required.

This PR's changes should be applied to 
https://github.com/dhlab-basel/Knora-ui/tree/wip/core-module-value-adaptation too. @flavens @kilchenmann    

closes #281

### CODE REVIEW

**Comment by benjamingeer** [comment]
Does it work with the Knora branch in https://github.com/dhlab-basel/Knora/pull/927 ?

**Comment by tobiasschweizer** [comment]
Yes, it does. The errors I got before I made the changes mentioned above were all related to the conversion of JSON-LD data representing resources with values, not the ontologies.

**Comment by benjamingeer** [comment]
Thanks for doing this!

**Comment by tobiasschweizer** [comment]
You are welcome.

**Comment by benjamingeer** [comment]
Can this be merged?

**Comment by tobiasschweizer** [comment]
@subotic Any chance that you can get the current import of BEOL online on the test-server with the current develop versions of Knora and Salsah?

**Comment by tobiasschweizer** [comment]
@flavens @kilchenmann I applied the same changes to https://github.com/dhlab-basel/Knora-ui/tree/wip/core-module-value-adaptation (https://github.com/dhlab-basel/Knora-ui/commit/18bfe87e184dc4601f5e4ff58b75a13141a62dfc)

**Pull request merged**
