### PR TITLE
Set list edit according to user permissions (only admins can edit)

### PR DESCRIPTION
**Pull request by sofiag**
create loggedInUser.projectAdmin to control user permissions, WIP

### CODE REVIEW

**Comment by sofiag** [comment]
@kilchenmann I could check the system admin, with password root@example.com, I don't have a project admin name+pwd, could you check this that it's working?

**Comment by kilchenmann** [comment]
The multi.user has the same password as the admin user. I tested it, but I don't have an edit nor an add button in lists view. Do you know how to fix it or should I have a deeper look into it?

**Comment by sofiag** [comment]
I can check. The add button comes directly from the framework for listings, I didn't change anything for it, it worked already before like this...

**Comment by sofiag** [comment]
or do you mean the add node button?

**Comment by kilchenmann** [comment]
I mean the add-new-list-button. Yes it's true, it comes from the framework-for-listings, which only checks if the user is a system admin and not if the user is project admin "only".

But all other buttons in the list itself (like edit list, add node etc.) were not visible.

I think we have to find a general solution to fix this. Right now I have no good idea how to do it.

**Comment by kilchenmann** [comment]
It should check, if the logged-in user is in the AdminGroup of this project: In AppConfig is the IRI for this group defined and you can use it with AppConfig.ProjectAdminGroup.
But we should write a user-cache-service (similar to the ontology-cache-service) to store the important information of the user. Right now we store some user data in the local storage, which shouldn't be used anymore.

**Comment by sofiag** [comment]
But the loggedInUser.projectAdmin exists and should work like the loggedInUser.sysAdmin. I'll check the AppConfig...

**Comment by sofiag** [comment]
I don't see how to check if the loggedInUser has project admin rights. loggedInUser has the attributes: email, sysAdmin (is a boolean) and token. What is the token exactly? Can we add also a projectAdmin and a projectMember attribute to the loggedInUser?

**Comment by kilchenmann** [comment]
Yes, the loggedInUser in localStorage has not so much information. But we want to omit this localStorage in the future (#216). So, I don't know, if we want to update the information now, to change it again in some weeks. But I can have a look on it next week.

**Comment by sofiag** [comment]
ok I can look a bit more into the appConfig but so far I couldn't see a better way to check who is the logged in user... I'd be good then if you also look into it next week.

**Comment by sofiag** [comment]
@kilchenmann I am looking into user.permissions.administrativePermissionsPerProject. Could this used to check if the logged in user is project admin?

**Comment by kilchenmann** [comment]
yes

On 27 Apr 2018, 12:57 +0200, Sofia Georgakopoulou <notifications@github.com>, wrote:

@kilchenmann<https://github.com/kilchenmann> I am looking into user.permissions.administrativePermissionsPerProject. Could this used to check if the logged in user is project admin?

**Comment by sofiag** [comment]
@kilchenmann what you have time, can you look into lines 149-158 of lists-list.component? I and extracting the logged in user from the localStorage. This only return an email and token. I use the email to get the full currentUser with the usersService. But this does not work. Any ideas? I feel I'm falling into an endless loop...

**Comment by kilchenmann** [comment]
will do that

**Comment by kilchenmann** [comment]
I implemented the usersService method to get the user data: You need to subscribe to the service method to get — in case of an error — the error message as well.

**Comment by sofiag** [comment]
Of course! I'm so stupid! haha, ok thanks @kilchenmann!

**Comment by kilchenmann** [comment]
Let me know, when you're done here. Then I can review it

**Comment by sofiag** [comment]
@kilchenmann can I merge?

**Comment by kilchenmann** [comment]
I think it's fine and it works.

The onHover-effect on the node wasn't clear enough. So tried to fix it with some simple styling hacks like highlighting and full-width size.
screen shot 2018-05-02 at 12 20 08

**Comment by sofiag** [comment]
ok, thanks! Yes, I didn't use much darkening. That's fine. I'll  merge.

**Pull request merged**
