### PR TITLE
Update node modules (Angular 5 incl. material)

### PR DESCRIPTION
**Pull request by kilchenmann**
update angular to version 5 incl. material (v5) and third party modules

### CODE REVIEW

**Comment by andreas-aeschlimann** [comment]
How can I help @kilchenmann?

**Comment by kilchenmann** [comment]
I just need a reviewer for this pull request. I thought, that you have the experience with the newest update of angular, which is a main part in this PR.

**Comment by andreas-aeschlimann** [comment]
The most careful you have to be when updating rxjs to at least 5.5. For me, this happened when I upgraded to Angular 5, so I am not sure why this didn't happen in your case.

In rxjs 5.5, you cannot use the regular "map", "catch" and so on anymore, because they introduced a new way in order to prevent collision with other libraries: https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md

Old example:

```
this.http
            .get(url)
            .map((response: Response) => {
                return this.jsonConvert.deserializeObject(response.json(), Search);
            })
            .catch((error: any) => {
                console.log(error);
                return Observable.throw("");
            });
```

New example:
```  
this.http
           .get(url)
           .pipe(
                map((response: Response) => {
                    return this.jsonConvert.deserializeObject(response, Search);
                }),
                catchError((error: any) => {
                    console.log(error);
                    return Observable.throw("");
                })
            );
```

Note the new "pipe" method that now has map as function, which is imported from rxjs operators:

`import { catchError, map } from "rxjs/operators";`

**Comment by musicEnfanthen** [comment]
Sorry for jumping in! 

During upgrade of my ng projects to v5 and cli v1.5 I encountered some problems because there are also many changes to other files. When you create a new empty cli project, there are changes to at least these files:
- `angular-cli.json`
- `karma.conf.js`
- `protractor.conf.js`
- `tsconfig.json`
- `tslint.json`
- `app.po.ts`
- `app.e2e-spec.ts`
- `tsconfig.e2e.json`
- `main.ts`
- `polyfills.ts`
- `test.ts`
- `tsconfig.app.json`
- `tsconfig.spec.json`
- `typings.d.ts`

Probably the easiest way to go would be to create a new empty cli project (with the same name [after renaming the old one to something like _XXX_old_]), adjust all projectspecific configurations in global files like
- `angular-cli.json`
- `package.json`
- `index.html`
- `styles.css`
(and whereelse you have projectspecific configurations)

and then copy the `app` folder from the old project to the new one (beside the helpful adaptions above from @andreas-aeschlimann and other ones mentioned on the [Angular Update Guide](https://angular-update-guide.firebaseapp.com/) this should work without problems). 

Going this way, ensures that you keep all of your code and at the same time have updated all angular specific files, preventing you from running into unforeseen problems in the future.

**Comment by kilchenmann** [comment]
I didn't update the node modules with an automatic command. I updated them manually and salsah is still running. What you're describing would be the next step in a separate branch. I just need the review here to make the merge now, because we need the newest version of material.

**Comment by sofiag** [comment]
The edit dialogue window does not open in full view anymore, is this as desired now?

**Comment by kilchenmann** [comment]
> The edit dialogue window does not open in full view anymore, is this as desired now?

No, this is new in material and I can't overwrite it anymore... But it doesn't matter at the moment. We will find a solution.

**Pull request merged**
